# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
minecraft_version=26.1.2
yarn_version=26.1.2+build.1
loader_version=0.18.2
fabric_api_version=0.150.0+26.1.2

# Mod Properties
mod_version = 0.3
maven_group = anticope.rejects
archives_base_name = meteor-rejects-addon

baritone_version=26.1
